const CONFIG = {
    titleWeb: "Gửi bánh đậu xanh của iêm",
    introTitle: 'Nguyễn Hoàng Long aka trưởng nhóm BigBang',
    introDesc: `	Có con chim nho nhỏ,
Đậu trên bãi cỏ xanh,
Có tình yêu không nhỏ,
Vẫn luôn dành cho anh. ٩(◕‿◕)۶`,
    btnIntro: '(ﾉ´ヮ`)ﾉ*: ･ﾟhề hề',
    title: 'Phải chăng em đã yêu ngay từ cái nhìn đầu tiên 🥰',
    desc: 'Phải chăng em đã say ngay từ lúc thấy nụ cười ấy ',
    btnYes: 'Ủa đương nhiên <33',
    btnNo: 'Không nha :3',
    question: 'Trên thế giới hơn 8 tỉ người mà sao bạn lại yêu mình <3',
    btnReply: 'Gửi cho bạn <3',
    reply: 'Yêu thì yêu mà không yêu thì yêu <33333333',
    mess: 'Mình biết mà 🥰. Yêu bạn nhiều nhiều 😘😘',
    messDesc: 'Happy Birthday my boy ạ',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'https://www.facebook.com/huynhduchaitruong' //link mess của các bạn. VD: https://www.facebook.com/messages/t/100014188333536
}
